data_dir = "data/"

PROJECTS_LIST = "projects_list.csv"
REPO_CSV_PATH = data_dir + "1_repo_info.csv"
MISSING_CSV_PATH = data_dir + "missing_repos.csv"
FORK_CSV_PATH = data_dir + "2_fork_info.csv"
REPO_COMMIT_CSV_PATH = data_dir + "3_repo_commit_info.csv"
FORK_COMMIT_CSV_PATH = data_dir + "4_fork_commit_info.csv"
REPO_PR_CSV_PATH = data_dir + "5_repo_pr_info.csv"
FORK_PR_CSV_PATH = data_dir + "6_fork_pr_info.csv"
STAR_CSV_PATH = data_dir + "7_star_info.csv"
RELEASE_CSV_PATH = data_dir + "8_release_info.csv"
RESUME_LOG_PATH_REPO_COMMIT = data_dir + "resume_log_repo_commit.txt"
RESUME_LOG_PATH_FORK_COMMIT = data_dir + "resume_log_fork_commit.txt"
RESUME_LOG_PATH_REPO_PR = data_dir + "resume_log_repo_pr.txt"
RESUME_LOG_PATH_FORK_PR = data_dir + "resume_log_fork_pr.txt"
RESUME_LOG_PATH_STAR = data_dir + "resume_log_star.txt"
RESUME_LOG_PATH_RELEASE = data_dir + "resume_log_release.txt"

SUSTAINABILITY_CSV_PATH = data_dir + "9_sustainability_data.csv"
REPO_FORK_COMMIT_PR_CSV_PATH = data_dir + "10_repo_fork_commit_pr_info.csv"
FINAL_CSV_PATH = data_dir + "11_final_data.csv"
